--create the tables which will normalize the data
CREATE TABLE PUBLISHER AS (SELECT DISTINCT HOSTNAME, PUBLISHER FROM PROJECT);
CREATE TABLE STORY AS (SELECT DISTINCT STORY, CATEGORY FROM PROJECT);
CREATE TABLE ARTICLE AS (SELECT DISTINCT ID, TITLE, URL, STORY, HOSTNAME, PUBLISHED_TIMESTAMP FROM PROJECT);

--fix the 2 records that were mistakenly missing the publisher - they're different in other regards
UPDATE PROJECT SET PUBLISHER=‘CBS Local’ WHERE PUBLISHER IS NULL;

--add primary and foreign keys
ALTER TABLE PUBLISHER ADD CONSTRAINT PUBLISHER_PK PRIMARY KEY(PUBLISHER, HOSTNAME);

ALTER TABLE STORY ADD CONSTRAINT STORY_PK PRIMARY KEY(STORY);

ALTER TABLE ARTICLE ADD CONSTRAINT ARTICLE_PK PRIMARY KEY(ID);
ALTER TABLE ARTICLE ADD CONSTRAINT ARTICLE_STORY_FK FOREIGN KEY(STORY) REFERENCES STORY(STORY);
ALTER TABLE ARTICLE ADD CONSTRAINT ARTICLE_PUBLISHER_FK FOREIGN KEY(PUBLISHER,HOSTNAME) REFERENCES PUBLISHER(PUBLISHER,HOSTNAME);