OPTIONS (skip=1)
LOAD DATA
INFILE ucinewsaggregator.csv
INTO TABLE PROJECT
REPLACE
FIELD TERMINATED BY ‘,’ OPTIONALLY ENCLOSED BY ‘”’
TRAILING NULLCOLS
(ID INTEGER EXTERNAL, TITLE, URL char(600), PUBLISHER, CATEGORY, STORY, HOSTNAME, PUBLISHED_TIMESTAMP DECIMAL EXTERNAL TERMINATED BY WHITESPACE)